[package]
name = "mycelium-computing-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Procedural macros for the mycelium modular DDS framework."
keywords = ["dds", "distributed", "macros"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true
name = "mycelium_computing_macros"

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = { version = "2.0.108", features = ["full"] }
