[package]
name = "usage_examples"
version.workspace = true
edition.workspace = true
publish = false
default-run = "usage_examples"

[[bin]]
name = "face_recognition"
path = "src/fake_face_recognition.rs"

[dependencies]
mycelium = { workspace = true, features = ["std_runtime"] }
dust_dds = { version = "0.15.0" }
rand = "0.10.0-rc.5"
smol = "2.0.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
